var headers = ['Præsens', 'Præteritum', 'Perfektum']

var verbs = [
  ['accepterer', 'accepterede', 'accepteret'],
  ['adskiller', 'adskilte', 'adskilt'],
  ['advarer', 'advarede', 'advaret'],
  ['afbryder', 'afbrød', 'afbrudt'],
  ['afgiver', 'afgav', 'afgivet'],
  ['afgør', 'afgjorde', 'afgjort'],
  ['afleverer', 'afleverede', 'afleveret'],
  ['aflyser', 'aflyste', 'aflyst'],
  ['afløser', 'afløste', 'afløst'],
  ['afskaffer', 'afskaffede', 'afskaffet'],
  ['afslutter', 'afsluttede', 'afsluttet'],
  ['afviser', 'afviste', 'afvist'],
  ['anbefaler', 'anbefalede', 'anbefalet'],
  ['anbringer', 'anbragte', 'anbragt'],
  ['aner', 'anede', 'anet'],
  ['anerkender', 'anerkendte', 'anerkendt'],
  ['angiver', 'angav', 'angivet'],
  ['angår', 'angik', 'angået'],
  ['anholder', 'anholdt', 'anholdt'],
  ['ankommer', 'ankom', 'ankommet'],
  ['anmelder', 'anmeldte', 'anmeldt'],
  ['anser', 'anså', 'anset'],
  ['ansætter', 'ansatte', 'ansat'],
  ['anvender', 'anvendte', 'anvendt'],
  ['arbejder', 'arbejdede', 'arbejdet'],
  ['arrangerer', 'arrangerede', 'arrangeret'],
  ['arresterer', 'arresterede', 'arresteret'],
  ['bager', 'bagte', 'bagt'],
  ['banker', 'bankede', 'banket'],
  ['beder', 'bad', 'bedt'],
  ['befinder', 'befandt', 'befundet'],
  ['begraver', 'begravede', 'begravet'],
  ['begrænser', 'begrænsede', 'begrænset'],
  ['begynder', 'begyndte', 'begyndt'],
  ['begår', 'begik', 'begået'],
  ['behandler', 'behandlede', 'behandlet'],
  ['beholder', 'beholdt', 'beholdt'],
  ['behøver', 'behøvede', 'behøvet'],
  ['beklager', 'beklagede', 'beklaget'],
  ['bemærker', 'bemærkede', 'bemærket'],
  ['benytter', 'benyttede', 'benyttet'],
  ['beskriver', 'beskrev', 'beskrevet'],
  ['beskytter', 'beskyttede', 'beskyttet'],
  ['beslutter', 'besluttede', 'besluttet'],
  ['bestemmer', 'bestemte', 'bestemt'],
  ['bestiller', 'bestilte', 'bestilt'],
  ['består', 'bestod', 'bestået'],
  ['besætter', 'besatte', 'besat'],
  ['besøger', 'besøgte', 'besøgt'],
  ['betaler', 'betalte', 'betalt'],
  ['betyder', 'betød', 'betydet'],
  ['bevarer', 'bevarede', 'bevaret'],
  ['beviser', 'beviste', 'bevist'],
  ['bider', 'bed', 'bidt'],
  ['bidrager', 'bidrog', 'bidraget'],
  ['binder', 'bandt', 'bundet'],
  ['blander', 'blandede', 'blandet'],
  ['bliver', 'blev', 'blevet'],
  ['blæser', 'blæste', 'blæst'],
  ['bor', 'boede', 'boet'],
  ['bringer', 'bragte', 'bragt'],
  ['bruger', 'brugte', 'brugt'],
  ['bryder', 'brød', 'brudt'],
  ['bygger', 'byggede', 'bygget'],
  ['bytter', 'byttede', 'byttet'],
  ['bærer', 'bar', 'båret'],
  ['citerer', 'citerede', 'citeret'],
  ['danner', 'dannede', 'dannet'],
  ['danser', 'dansede', 'danset'],
  ['deler', 'delte', 'delt'],
  ['deltager', 'deltog', 'deltaget'],
  ['diskuterer', 'diskuterede', 'diskuteret'],
  ['dominerer', 'dominerede', 'domineret'],
  ['drager', 'drog', 'draget'],
  ['drejer', 'drejede', 'drejet'],
  ['drikker', 'drak', 'drukket'],
  ['driver', 'drev', 'drevet'],
  ['dræber', 'dræbte', 'dræbt'],
  ['drøfter', 'drøftede', 'drøftet'],
  ['drømmer', 'drømte', 'drømt'],
  ['dækker', 'dækkede', 'dækket'],
  ['dør', 'døde', 'død'],
  ['dømmer', 'dømte', 'dømt'],
  ['efterlader', 'efterlod', 'efterladt'],
  ['ejer', 'ejede', 'ejet'],
  ['eksisterer', 'eksisterede', 'eksisteret'],
  ['elsker', 'elskede', 'elsket'],
  ['ender', 'endte', 'endt'],
  ['erkender', 'erkendte', 'erkendt'],
  ['falder', 'faldt', 'faldet'],
  ['fanger', 'fangede', 'fanget'],
  ['fastholder', 'fastholdt', 'fastholdt'],
  ['fastsætter', 'fastsatte', 'fastsat'],
  ['fatter', 'fattede', 'fattet'],
  ['fejrer', 'fejrede', 'fejret'],
  ['finder', 'fandt', 'fundet'],
  ['fjerner', 'fjernede', 'fjernet'],
  ['flygter', 'flygtede', 'flygtet'],
  ['flytter', 'flyttede', 'flyttet'],
  ['fodrer', 'fodrede', 'fodret'],
  ['forbedrer', 'forbedrede', 'forbedret'],
  ['forbereder', 'forberedte', 'forberedt'],
  ['forbliver', 'forblev', 'forblevet'],
  ['fordeler', 'fordelte', 'fordelt'],
  ['foregår', 'foregik', 'foregået'],
  ['forekommer', 'forekom', 'forekommet'],
  ['forener', 'forenede', 'forenet'],
  ['foreslår', 'foreslog', 'foreslået'],
  ['foretrækker', 'foretrak', 'foretrukket'],
  ['forhandler', 'forhandlede', 'forhandlet'],
  ['forhindrer', 'forhindrede', 'forhindret'],
  ['forklarer', 'forklarede', 'forklaret'],
  ['forlader', 'forlod', 'forladt'],
  ['forlanger', 'forlangte', 'forlangt'],
  ['formulerer', 'formulerede', 'formuleret'],
  ['forsinker', 'forsinkede', 'forsinket'],
  ['forstår', 'forstod', 'forstået'],
  ['forsvarer', 'forsvarede', 'forsvaret'],
  ['forsvinder', 'forsvandt', 'forsvundet'],
  ['forsøger', 'forsøgte', 'forsøgt'],
  ['fortjener', 'fortjente', 'fortjent'],
  ['fortæller', 'fortalte', 'fortalt'],
  ['forvandler', 'forvandlede', 'forvandlet'],
  ['forventer', 'forventede', 'forventet'],
  ['fremgår', 'fremgik', 'fremgået'],
  ['fremhæver', 'fremhævede', 'fremhævet'],
  ['fremlægger', 'fremlagde', 'fremlagt'],
  ['fremstiller', 'fremstillede', 'fremstillet'],
  ['fremsætter', 'fremsatte', 'fremsat'],
  ['frister', 'fristede', 'fristet'],
  ['frygter', 'frygtede', 'frygtet'],
  ['fungerer', 'fungerede', 'fungeret'],
  ['fylder', 'fyldte', 'fyldt'],
  ['fyrer', 'fyrede', 'fyret'],
  ['føder', 'fødte', 'født'],
  ['føler', 'følte', 'følt'],
  ['følger', 'fulgte', 'fulgt'],
  ['fører', 'førte', 'ført'],
  ['får', 'fik', 'fået'],
  ['gemmer', 'gemte', 'gemt'],
  ['generer', 'generede', 'generet'],
  ['gennemfører', 'gennemførte', 'gennemført'],
  ['gennemgår', 'gennemgik', 'gennemgået'],
  ['gentager', 'gentog', 'gentaget'],
  ['gider', 'gad', 'gidet'],
  ['giver', 'gav', 'givet'],
  ['glemmer', 'glemte', 'glemt'],
  ['glider', 'gled', 'gledet'],
  ['godkender', 'godkendte', 'godkendt'],
  ['griber', 'greb', 'grebet'],
  ['griner', 'grinede', 'grinet'],
  ['græder', 'græd', 'grædt'],
  ['gør', 'gjorde', 'gjort'],
  ['hader', 'hadede', 'hadet'],
  ['handler', 'handlede', 'handlet'],
  ['har', 'havde', 'haft'],
  ['hedder', 'hed', 'heddet'],
  ['henter', 'hentede', 'hentet'],
  ['henviser', 'henviste', 'henvist'],
  ['hersker', 'herskede', 'hersket'],
  ['hilser', 'hilste', 'hilst'],
  ['hindrer', 'hindrede', 'hindret'],
  ['hjælper', 'hjalp', 'hjulpet'],
  ['holder', 'holdt', 'holdt'],
  ['husker', 'huskede', 'husket'],
  ['hvisker', 'hviskede', 'hvisket'],
  ['hælder', 'hældte', 'hældt'],
  ['hævder', 'hævdede', 'hævdet'],
  ['hæver', 'hævede', 'hævet'],
  ['hører', 'hørte', 'hørt'],
  ['håber', 'håbede', 'håbet'],
  ['inddrager', 'inddrog', 'inddraget'],
  ['indebærer', 'indebar', 'indebåret'],
  ['indeholder', 'indeholdt', 'indeholdt'],
  ['indfører', 'indførte', 'indført'],
  ['indgår', 'indgik', 'indgået'],
  ['indleder', 'indledte', 'indledt'],
  ['indretter', 'indrettede', 'indrettet'],
  ['indrømmer', 'indrømmede', 'indrømmet'],
  ['indstiller', 'indstillede', 'indstillet'],
  ['indtager', 'indtog', 'indtaget'],
  ['installerer', 'installerede', 'installeret'],
  ['inspirerer', 'inspirerede', 'inspireret'],
  ['interesserer', 'interesserede', 'interesseret'],
  ['investerer', 'investerede', 'investeret'],
  ['inviterer', 'inviterede', 'inviteret'],
  ['irriterer', 'irriterede', 'irriteret'],
  ['kalder', 'kaldte', 'kaldt'],
  ['kaster', 'kastede', 'kastet'],
  ['kender', 'kendte', 'kendt'],
  ['kigger', 'kiggede', 'kigget'],
  ['klarer', 'klarede', 'klaret'],
  ['klipper', 'klippede', 'klippet'],
  ['klæder', 'klædte', 'klædt'],
  ['knuser', 'knuste', 'knust'],
  ['knytter', 'knyttede', 'knyttet'],
  ['koger', 'kogte', 'kogt'],
  ['kombinerer', 'kombinerede', 'kombineret'],
  ['kommer', 'kom', 'kommet'],
  ['kommenterer', 'kommenterede', 'kommenteret'],
  ['konstaterer', 'konstaterede', 'konstateret'],
  ['kontakter', 'kontaktede', 'kontaktet'],
  ['kontrollerer', 'kontrollerede', 'kontrolleret'],
  ['koster', 'kostede', 'kostet'],
  ['kritiserer', 'kritiserede', 'kritiseret'],
  ['kræver', 'krævede', 'krævet'],
  ['kan', 'kunne', 'kunnet'],
  ['kysser', 'kyssede', 'kysset'],
  ['kæmper', 'kæmpede', 'kæmpet'],
  ['køber', 'købte', 'købt'],
  ['lader', 'lod', 'ladet'],
  ['lander', 'landede', 'landet'],
  ['laver', 'lavede', 'lavet'],
  ['ler', 'lo', 'leet'],
  ['leder', 'ledte', 'ledt'],
  ['leger', 'legede', 'leget'],
  ['lejer', 'lejede', 'lejet'],
  ['lever', 'levede', 'levet'],
  ['leverer', 'leverede', 'leveret'],
  ['lider', 'led', 'lidt'],
  ['ligner', 'lignede', 'lignet'],
  ['lokker', 'lokkede', 'lokket'],
  ['lover', 'lovede', 'lovet'],
  ['lukker', 'lukkede', 'lukket'],
  ['lyder', 'lød', 'lydt'],
  ['lykkes', 'lykkedes', 'lykkedes'],
  ['lyser', 'lyste', 'lyst'],
  ['lytter', 'lyttede', 'lyttet'],
  ['lærer', 'lærte', 'lært'],
  ['læser', 'læste', 'læst'],
  ['løfter', 'løftede', 'løftet'],
  ['løser', 'løste', 'løst'],
  ['låner', 'lånte', 'lånt'],
  ['maler', 'malede', 'malet'],
  ['mangler', 'manglede', 'manglet'],
  ['meddeler', 'meddelte', 'meddelt'],
  ['medfører', 'medførte', 'medført'],
  ['medvirker', 'medvirkede', 'medvirket'],
  ['melder', 'meldte', 'meldt'],
  ['mener', 'mente', 'ment'],
  ['minder', 'mindede', 'mindet'],
  ['mister', 'mistede', 'mistet'],
  ['modtager', 'modtog', 'modtaget'],
  ['myrder', 'myrdede', 'myrdet'],
  ['mærker', 'mærkede', 'mærket'],
  ['møder', 'mødte', 'mødt'],
  ['mødes', 'mødtes', 'mødtes'],
  ['måler', 'målte', 'målt'],
  ['må', 'måtte', 'måttet'],
  ['nedlægger', 'nedlagde', 'nedlagt'],
  ['nedsætter', 'nedsatte', 'nedsat'],
  ['nikker', 'nikkede', 'nikket'],
  ['noterer', 'noterede', 'noteret'],
  ['nyder', 'nød', 'nydt'],
  ['nægter', 'nægtede', 'nægtet'],
  ['offentliggør', 'offentliggjorde', 'offentlig-gjort'],
  ['omfatter', 'omfattede', 'omfattet'],
  ['omgiver', 'omgav', 'omgivet'],
  ['opbygger', 'opbyggede', 'opbygget'],
  ['opdager', 'opdagede', 'opdaget'],
  ['opererer', 'opererede', 'opereret'],
  ['opfatter', 'opfattede', 'opfattet'],
  ['opfinder', 'opfandt', 'opfundet'],
  ['opfordrer', 'opfordrede', 'opfordret'],
  ['opfylder', 'opfyldte', 'opfyldt'],
  ['opfører', 'opførte', 'opført'],
  ['opgiver', 'opgav', 'opgivet'],
  ['ophæver', 'ophævede', 'ophævet'],
  ['oplever', 'oplevede', 'oplevet'],
  ['oplyser', 'oplyste', 'oplyst'],
  ['opnår', 'opnåede', 'opnået'],
  ['opretter', 'oprettede', 'oprettet'],
  ['opstiller', 'opstillede', 'opstillet'],
  ['opstår', 'opstod', 'opstået'],
  ['optager', 'optog', 'optaget'],
  ['optræder', 'optrådte', 'optrådt'],
  ['orienterer', 'orienterede', 'orienteret'],
  ['overbeviser', 'overbeviste', 'overbevist'],
  ['overfører', 'overførte', 'overført'],
  ['overholder', 'overholdt', 'overholdt'],
  ['overlader', 'overlod', 'overladt'],
  ['overlever', 'overlevede', 'overlevet'],
  ['overrasker', 'overraskede', 'overrasket'],
  ['overtager', 'overtog', 'overtaget'],
  ['overvejer', 'overvejede', 'overvejet'],
  ['pakker', 'pakkede', 'pakket'],
  ['passer', 'passede', 'passet'],
  ['peger', 'pegede', 'peget'],
  ['placerer', 'placerede', 'placeret'],
  ['planlægger', 'planlagde', 'planlagt'],
  ['plejer', 'plejede', 'plejet'],
  ['presser', 'pressede', 'presset'],
  ['producerer', 'producerede', 'produceret'],
  ['præger', 'prægede', 'præget'],
  ['præsenterer', 'præsenterede', 'præsenteret'],
  ['prøver', 'prøvede', 'prøvet'],
  ['pudser', 'pudsede', 'pudset'],
  ['påvirker', 'påvirkede', 'påvirket'],
  ['rammer', 'ramte', 'ramt'],
  ['reagerer', 'reagerede', 'reageret'],
  ['redder', 'reddede', 'reddet'],
  ['reducerer', 'reducerede', 'reduceret'],
  ['registrerer', 'registrerede', 'registreret'],
  ['regner', 'regnede', 'regnet'],
  ['renser', 'rensede', 'renset'],
  ['repræsenterer', 'repræsenterede', 'repræsen-teret'],
  ['respekterer', 'respekterede', 'respekteret'],
  ['retter', 'rettede', 'rettet'],
  ['rider', 'red', 'redet'],
  ['ringer', 'ringede', 'ringet'],
  ['risikerer', 'risikerede', 'risikeret'],
  ['river', 'rev', 'revet'],
  ['roser', 'roste', 'rost'],
  ['rummer', 'rummede', 'rummet'],
  ['rydder', 'ryddede', 'ryddet'],
  ['ryger', 'røg', 'røget'],
  ['rykker', 'rykkede', 'rykket'],
  ['ryster', 'rystede', 'rystet'],
  ['rækker', 'rakte', 'rakt'],
  ['rører', 'rørte', 'rørt'],
  ['råber', 'råbte', 'råbt'],
  ['råder', 'rådede', 'rådet'],
  ['samler', 'samlede', 'samlet'],
  ['sammenligner', 'sammenlignede', 'sammen-lignet'],
  ['satser', 'satsede', 'satset'],
  ['savner', 'savnede', 'savnet'],
  ['ser', 'så', 'set'],
  ['sejler', 'sejlede', 'sejlet'],
  ['sender', 'sendte', 'sendt'],
  ['serverer', 'serverede', 'serveret'],
  ['ses', 'sås', 'sets'],
  ['sidder', 'sad', 'siddet'],
  ['sikrer', 'sikrede', 'sikret'],
  ['skaber', 'skabte', 'skabt'],
  ['skader', 'skadede', 'skadet'],
  ['skaffer', 'skaffede', 'skaffet'],
  ['sker', 'skete', 'sket'],
  ['skifter', 'skiftede', 'skiftet'],
  ['skinner', 'skinnede', 'skinnet'],
  ['skjuler', 'skjulte', 'skjult'],
  ['skriger', 'skreg', 'skreget'],
  ['skriver', 'skrev', 'skrevet'],
  ['skræmmer', 'skræmte', 'skræmt'],
  ['skubber', 'skubbede', 'skubbet'],
  ['skuffer', 'skuffede', 'skuffet'],
  ['skal', 'skulle', 'skullet'],
  ['skyder', 'skød', 'skudt'],
  ['skyldes', 'skyldtes', 'skyldtes'],
  ['skærer', 'skar', 'skåret'],
  ['slukker', 'slukkede', 'slukket'],
  ['slutter', 'sluttede', 'sluttet'],
  ['slår', 'slog', 'slået'],
  ['slås', 'sloges', 'sloges'],
  ['smager', 'smagte', 'smagt'],
  ['smider', 'smed', 'smidt'],
  ['smiler', 'smilede', 'smilet'],
  ['smitter', 'smittede', 'smittet'],
  ['snakker', 'snakkede', 'snakket'],
  ['sover', 'sov', 'sovet'],
  ['sparer', 'sparede', 'sparet'],
  ['spiller', 'spillede', 'spillet'],
  ['spiser', 'spiste', 'spist'],
  ['spreder', 'spredte', 'spredt'],
  ['spørger', 'spurgte', 'spurgt'],
  ['stammer', 'stammede', 'stammet'],
  ['stemmer', 'stemte', 'stemt'],
  ['steger', 'stegte', 'stegt'],
  ['stiger', 'steg', 'steget'],
  ['stikker', 'stak', 'stukket'],
  ['stiller', 'stillede', 'stillet'],
  ['stjæler', 'stjal', 'stjålet'],
  ['straffer', 'straffede', 'straffet'],
  ['strammer', 'strammede', 'strammet'],
  ['strækker', 'strakte', 'strakt'],
  ['studerer', 'studerede', 'studeret'],
  ['styrer', 'styrede', 'styret'],
  ['styrker', 'styrkede', 'styrket'],
  ['støder', 'stødte', 'stødt'],
  ['støtter', 'støttede', 'støttet'],
  ['står', 'stod', 'stået'],
  ['svarer', 'svarede', 'svaret'],
  ['svinger', 'svingede', 'svinget'],
  ['syr', 'syede', 'syet'],
  ['synes', 'syntes', 'syntes'],
  ['synger', 'sang', 'sunget'],
  ['synker', 'sank', 'sunket'],
  ['sælger', 'solgte', 'solgt'],
  ['sænker', 'sænkede', 'sænket'],
  ['sætter', 'satte', 'sat'],
  ['søger', 'søgte', 'søgt'],
  ['taber', 'tabte', 'tabt'],
  ['tager', 'tog', 'taget'],
  ['takker', 'takkede', 'takket'],
  ['taler', 'talte', 'talt'],
  ['tegner', 'tegnede', 'tegnet'],
  ['tilbringer', 'tilbragte', 'tilbragt'],
  ['tilbyder', 'tilbød', 'tilbudt'],
  ['tilføjer', 'tilføjede', 'tilføjet'],
  ['tilhører', 'tilhørte', 'tilhørt'],
  ['tillader', 'tillod', 'tilladt'],
  ['tjener', 'tjente', 'tjent'],
  ['tror', 'troede', 'troet'],
  ['truer', 'truede', 'truet'],
  ['trykker', 'trykkede', 'trykket'],
  ['træder', 'trådte', 'trådt'],
  ['træffer', 'traf', 'truffet'],
  ['trækker', 'trak', 'trukket'],
  ['trænger', 'trængte', 'trængt'],
  ['tør', 'turde', 'turdet'],
  ['tvinger', 'tvang', 'tvunget'],
  ['tyder', 'tydede', 'tydet'],
  ['tæller', 'talte', 'talt'],
  ['tænder', 'tændte', 'tændt'],
  ['tænker', 'tænkte', 'tænkt'],
  ['tømmer', 'tømte', 'tømt'],
  ['tørrer', 'tørrede', 'tørret'],
  ['tåler', 'tålte', 'tålt'],
  ['udarbejder', 'udarbejdede', 'udarbejdet'],
  ['udbreder', 'udbredte', 'udbredt'],
  ['uddanner', 'uddannede', 'uddannet'],
  ['udelukker', 'udelukkede', 'udelukket'],
  ['udfører', 'udførte', 'udført'],
  ['udgiver', 'udgav', 'udgivet'],
  ['udgør', 'udgjorde', 'udgjort'],
  ['udkommer', 'udkom', 'udkommet'],
  ['udleverer', 'udleverede', 'udleveret'],
  ['udløser', 'udløste', 'udløst'],
  ['udnytter', 'udnyttede', 'udnyttet'],
  ['udstyrer', 'udstyrede', 'udstyret'],
  ['udsætter', 'udsatte', 'udsat'],
  ['udtaler', 'udtalte', 'udtalt'],
  ['udtrykker', 'udtrykte', 'udtrykt'],
  ['udvider', 'uvidede', 'udvidet'],
  ['udvikler', 'udviklede', 'udviklet'],
  ['underholder', 'underholdt', 'underholdt'],
  ['under-streger', 'understregede', 'under-streget'],
  ['undersøger', 'undersøgte', 'undersøgt'],
  ['undgår', 'undgik', 'undgået'],
  ['vaccinerer', 'vaccinerede', 'vaccineret'],
  ['varer', 'varede', 'varet'],
  ['varierer', 'varierede', 'varieret'],
  ['vasker', 'vaskede', 'vasket'],
  ['vedtager', 'vedtog', 'vedtaget'],
  ['vejer', 'vejede', 'vejet'],
  ['vender', 'vendte', 'vendt'],
  ['venter', 'ventede', 'ventet'],
  ['ved', 'vidste', 'vidst'],
  ['vil', 'ville', 'villet'],
  ['vinder', 'vandt', 'vundet'],
  ['virker', 'virkede', 'virket'],
  ['viser', 'viste', 'vist'],
  ['vokser', 'voksede', 'vokset'],
  ['vurderer', 'vurderede', 'vurderet'],
  ['vækker', 'vækkede', 'vækket'],
  ['vælger', 'valgte', 'valgt'],
  ['vælter', 'væltede', 'væltet'],
  ['er', 'var', 'været'],
  ['vågner', 'vågnede', 'vågnet'],
  ['yder', 'ydede', 'ydet'],
  ['ændrer', 'ændrede', 'ændret'],
  ['ødelægger', 'ødelagde', 'ødelagt'],
  ['øger', 'øgede', 'øget'],
  ['ønsker', 'ønskede', 'ønsket'],
  ['åbner', 'åbnede', 'åbnet']
];

function  filterVerbs()
{
  var oldTable = document.querySelector('table');
  var newTable = document.createElement('table');
  var filterString = document.getElementById('filter').value;

  var tr = document.createElement('tr');
  for (var header = 0; header < 3; header++) {    
    var th = document.createElement('th');
    var text = document.createTextNode(headers[header]);
    th.appendChild(text);
    tr.appendChild(th);
  }
  newTable.appendChild(tr);

  var rowsDisplayed = verbs.length;
  for (var row = 0; row < verbs.length; row++) {
    var stringFound = false;

    var tr = document.createElement('tr');
    for (var column = 0; column < 3; column++) {
      var verbForm = verbs[row][column];

      if (verbForm.includes(filterString)) {
        stringFound = true;
      }

      var td = document.createElement('td');
      var text = document.createTextNode(verbForm);
      td.appendChild(text);
      tr.appendChild(td);
    }

    if (stringFound === true) {
      newTable.appendChild(tr);
    }
    else {
      rowsDisplayed--;
    }
  }

  oldTable.parentNode.replaceChild(newTable, oldTable);

  var oldP = document.querySelector('p');
  var newP = document.createElement('p');
  var text = document.createTextNode(rowsDisplayed == verbs.length ? "Showing all " + verbs.length + " verbs." : "Showing " + rowsDisplayed + " of " + verbs.length + " verbs.");
  newP.appendChild(text);
  oldP.parentNode.replaceChild(newP, oldP);
}